# D1：NumPy陣列定義與屬性

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])

print(type(a)) # <type 'numpy.ndarray'>

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [3]:
print(a.ndim) # 2
print(a.shape) # (3,5)
print(a.size) # 15
print(a.dtype) # int32
print(a.itemsize) # 4
print(a.data) # <memory at 0x00000296AB488828> 

2
(3, 5)
15
int32
4


In [4]:
list(a)
# [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [5]:
a.tolist()
# [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

# D2：NumPy陣列資料型態

In [7]:
print(a.dtype == 'int32') # True
print(a.dtype is 'int32') # False
print(a.dtype is np.dtype('int32')) # True

True
False
True


In [8]:
print(a.dtype == 'int') 
print(a.dtype == np.int) 
print(a.dtype == np.dtype('int')) 

True
True
True


# D3：NumPy陣列的初始化

In [10]:
print(np.arange( 10, 30, 5 ))
# array([10, 15, 20, 25])
print(np.linspace( 0, 2, 3 ))
# array([0. 1. 2.])
print(np.logspace( 0, 2, 3 ))
# array([1. 10. 100.])

[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]


In [19]:
from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2)) # 3*2 array，元素值取3*2次符合Normal(mu=0,sigma=1)的值
random = rng.random((3,2)) # 3*2 array，元素值取3*2次[0,1)中的float值(均勻)
integers = rng.integers(0, 10, size=(3,2)) # 3*2 array，元素值取3*2次[0,10)中的值

print(normal)
print(random)
print(integers)

[[ 1.2361904   1.15169374]
 [ 0.08386839 -1.21398297]
 [ 0.38800389  2.1422208 ]]
[[0.34783311 0.07435547]
 [0.38373747 0.57392032]
 [0.39060422 0.59626724]]
[[3 6]
 [2 8]
 [3 1]]


In [23]:
dt = np.dtype({'names':('Name', 'num1', 'num2', 'True'), 'formats':((np.str_, 5), np.int32, int, 'U3')})
c = np.zeros(3, dtype=dt)
c

array([('', 0, 0, ''), ('', 0, 0, ''), ('', 0, 0, '')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

In [24]:
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

c['Name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['True'] = check
print(c)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]


In [25]:
c_rec = c.view(np.recarray)
c_rec

rec.array([('Chloe', 11, 14, 'Y'), ('Charl', 12, 15, 'Y'),
           ('Clara', 13, 16, 'N')],
          dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

In [26]:
c_rec.Name

array(['Chloe', 'Charl', 'Clara'], dtype='<U5')

# D4：NumPy陣列的算數運算

In [2]:
import numpy as np

a = np.array([[1.0, 2.0], [3.0, 4.0]])
# [[1. 2.]
#  [3. 4.]]
y = np.array([[5.], [7.]])
# [[5.]]
#  [7.]]

print(a.transpose()) # 非永久改變a
# array([[1., 3.],
#        [2., 4.]])
print(np.linalg.inv(a)) # inverse of a
# array([[-2. ,  1. ],
#        [ 1.5, -0.5]])
print(np.trace(a))
# 2.0
print(np.linalg.solve(a, y))  # ax = y 的解
# array([[-3.],
#        [ 4.]])

[[1. 3.]
 [2. 4.]]
[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]


In [3]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
# [[1. 2.]
#  [3. 4.]] 

a_inv = np.linalg.inv(a)
# array([[-2.  ,  1. ],
#   [ 1.5, -0.5]])

I = np.dot(a,a_inv)

print(I)
# [[1.0000000e+00 0.0000000e+00]
#  [8.8817842e-16 1.0000000e+00]]

print(np.around(I))
#[[1. 0.]
# [0. 1.]]
print(I.astype(np.int64))
#[[1 0]
# [0 0]]

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
[[0 0]
 [0 1]]


# D5：NumPy陣列的邏輯運算

In [5]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
# 比較運算
print(a > b) # [ True  True  True  True]
print(a < b) # [False False False False]
print(a == b) # [False False False False]
print(a != b) # [ True  True  True  True]

a = np.array( [True, True, False, False] )
b = np.array( [True, False, True, False]  )
# 邏輯運算
#print(a and b) # ValueError

# 位元運算
print(a & b) # [ True False False False]
print(a | b) # [ True  True  True False]

[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]
[ True False False False]
[ True  True  True False]


In [6]:
import numpy as np

a = np.array( [10, 20, 30, 40] )

print(a[ [True, True, True, True] ])
# [10 20 30 40]
print(a[ [True, False, True, False] ])
# [10 30]
print(a[ [False, False, False, False] ])
# []

[10 20 30 40]
[10 30]
[]


In [10]:
import numpy as np

a = np.array( [10, 20, 30, 40] )
print(a > 20) # 單純印出bool值
# [False False  True  True]
print(a[ [False, False, True, True] ]) # 將bool值與a一一結合，只印出被定義為True的element
# [30 40] 
print(a[ a > 20 ]) # 結合bool值，只印True的element
# [30 40] 

# python容器做法
b = []
for i in a:
  if i > 20:
    b.append(i)
print(b) # [30, 40]

[False False  True  True]
[30 40]
[30 40]
[30, 40]


In [11]:
import numpy as np

print(np.any([True, True, True])) # True
print(np.any([True, False, False])) # True
print(np.any([False, False, False])) # False

print(np.all([True, True, True])) # True
print(np.all([True, False, False])) # False
print(np.all([False, False, False])) # False

True
True
False
True
False
False


# D6：NumPy中常見的陣列方法與函式

In [19]:
import numpy as np 

print(np.searchsorted([1,2,3,4,5], 3))# 2
print(np.searchsorted(
    [1, 2, 5, 4, 3],
    [-10, 10, 3, 5]
))# [0, 5, 2, 5]
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [-10, 10, 3, 5]
))# [0, 5, 2, 4]

2
[0 5 2 5]
[0 5 2 4]


In [26]:
a = np.arange(10)
print(np.where(a, 1, -1)) # [-1  1  1  1  1  1  1  1  1  1]
print(np.where(a > 5, 1, -1)) # [-1 -1 -1 -1 -1 -1  1  1  1  1]
print(np.where([[True,False], [True,True]],    # 第一個True對應x,y的1和9，因為要True，所以選1，其他以此類推
			 [[1,2], [3,4]],
             [[9,8], [7,6]]))
# [[1, 8],
#  [3, 4]]

a = np.array([2, 4, 6, 8, 10])
print(np.where(a>5)) # (array([2, 3, 4], dtype=int64),)
print(a[np.where(a>5)]) # [6 8 10]

print(np.where([[0, 1], [1, 0]]))  # 會return True的是value=1的element，座標分別是(0,1),(1,0)
# (array([0, 1], dtype=int64), array([1, 0], dtype=int64))

[-1  1  1  1  1  1  1  1  1  1]
[-1 -1 -1 -1 -1 -1  1  1  1  1]
[[1 8]
 [3 4]]
(array([2, 3, 4], dtype=int64),)
[ 6  8 10]
(array([0, 1], dtype=int64), array([1, 0], dtype=int64))


In [41]:
import numpy as np 

a = np.arange(6) # [0, 1, 2, 3, 4, 5]
print(a.reshape(3, -1)) # 新形狀可模糊指定為-1，numpy會自動計算
print(a.reshape(3, 2))
# [[0 1]
#  [2 3]
#  [4 5]]
a.reshape(3,2)[0,0] = 100
print(a) # [100, 1, 2, 3, 4, 5] 本身的值也被改變了

a = np.arange(6) # [0, 1, 2, 3, 4, 5]
print(a.resize((3, 2))) # None
print(a)
# [[0 1]
#  [2 3]
#  [4 5]]
a.resize(3, 1)
print(a)
# [[0]
# [1]
# [2]]
a.resize(3, 3)
print(a)
# [[0 1 2]
# [0 0 0]
# [0 0 0]]

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[100   1   2   3   4   5]
None
[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [0 0 0]
 [0 0 0]]


In [35]:
a = np.arange(6).reshape((3, 2))
print(a.ravel()) # [0 1 2 3 4 5]
a.ravel()[1] = 100
print(a.flatten()) # [  0 100   2   3   4   5] a被改動了
print(a.flat) # <numpy.flatiter object at 0x0000022788329B50>
print(a.flat[2]) # 2

[0 1 2 3 4 5]
[  0 100   2   3   4   5]
2


# D7：NumPy陣列的索引、切片與迭代

In [1]:
import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in a.flat:
    print(d)

0
1
2
3
4
5


In [5]:
ls = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
      [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
a = np.array(ls, dtype=int)
print(a)
print(a.strides)

SyntaxError: invalid character in identifier (<ipython-input-5-786b211015c0>, line 1)