# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np
print(np.zeros((2, 3))) # 建立2*3 array，初始值均為0
print(np.empty((2, 3))) # 建立2*3 array，不設定初始值(視為None)，也因此建array速度會較np.zeros()稍快

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [19]:
# 參考解答
a = np.random.rand(2, 3)
a = a * 100
cop_a = a
print(a)

# method1
print(np.round_(a))

# method2
cop_a = cop_a + 0.5
print(np.floor(cop_a))

[[84.37972504  9.12107522  5.7328184 ]
 [71.60016595 94.77562983 55.94815969]]
[[84.  9.  6.]
 [72. 95. 56.]]
[[84.  9.  6.]
 [72. 95. 56.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [21]:
m = 20
n = 40
a = np.random.rand(2, 3) * (n - m) + m # 將[0,1)長度1拓展至長度(n-m)，再加上
print(a)
print(np.round_(a))

[[23.86827241 31.77445251 27.6907715 ]
 [20.39551876 22.95187521 35.11105692]]
[[24. 32. 28.]
 [20. 23. 35.]]
