# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np
a = np.arange(5)
print(a.sum()) # 10
print(np.sum(a)) # 10
print(sum(a)) # 10

b = [0, 1, 2, 3, 4]
#print(b.sum()) # AttributeError：list無.sum()這個屬性
print(np.sum(b)) # 10
print(sum(b)) # 10

10
10
10
10
10


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。
normalization
https://ithelp.ithome.com.tw/articles/10197357
https://blog.csdn.net/kane7csdn/article/details/86475918

In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))
print(A)

B = (A - np.min(A)) / (np.max(A) - np.min(A))
print(B)

[[0.25377867 0.70060774 0.75997929 0.69203493 0.00681379]
 [0.10447512 0.16844332 0.72988094 0.62096046 0.35686748]
 [0.98938342 0.64169993 0.50768256 0.713419   0.1389183 ]
 [0.279287   0.71363777 0.57827034 0.62357702 0.10833031]
 [0.23927666 0.90890287 0.57445112 0.97183374 0.09161532]]
[[0.25134593 0.70610156 0.76652634 0.69737668 0.        ]
 [0.0993938  0.16449678 0.73589406 0.62504137 0.3562635 ]
 [1.         0.64614876 0.50975397 0.71914009 0.13444799]
 [0.27730677 0.71936274 0.58159396 0.62770435 0.10331738]
 [0.23658667 0.91809176 0.57770698 0.982139   0.08630588]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
a = np.arange(10)
print(a)
a[a == np.max(a)] = -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8 -1]
