# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件
import numpy as np

a = np.arange(11) + 1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [7]:
a[(a >= 3) & (a <= 6)] = -a[(a >= 3) & (a <= 6)]
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [10]:
A = np.random.rand(3, 6)
print(A)
print(A[A > 0.5].size)

[[0.87011058 0.70886587 0.6965066  0.89408522 0.90371726 0.72220283]
 [0.12319963 0.50255247 0.37903137 0.3065905  0.30151558 0.46939701]
 [0.63212128 0.52326334 0.56046857 0.10619825 0.87261523 0.93217521]]
12
