# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
# list(a)只會將最高維度的元素轉為list
# a.tolist則會將所有維度的元素全部轉為list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
a = np.random.randint(10, size=6) 
print(a) # a是取6次[0,10)中隨機出的整數所構成的1維陣列
print(a.ndim) # 維度個數
print(a.shape) # 陣列形狀
print(a.size) # 元素總數
print(a.dtype) # 元素資料型態
print(a.itemsize) # 每個元素占用的空間大小(byte)
print(len(a)) # 陣列長度
print(type(a)) # a的變數型態

[2 2 9 9 6 6]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b) # b是取3*4次[0,10)中隨機出的整數所構成的2維陣列
print(b.ndim) # 維度個數
print(b.shape) # 陣列形狀
print(b.size) # 元素總數
print(b.dtype) # 元素資料型態
print(b.itemsize) # 每個元素占用的空間大小(byte)
print(len(b)) # 陣列長度
print(type(b)) # b的變數型態

[[5 9 2 2]
 [0 3 2 0]
 [0 3 3 3]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 
print(c) # c是取2*3*2次[0,10)中隨機出的整數所構成的3維陣列
print(c.ndim) # 維度個數
print(c.shape) # 陣列形狀
print(c.size) # 元素總數
print(c.dtype) # 元素資料型態
print(c.itemsize) # 每個元素占用的空間大小(byte)
print(len(c)) # 陣列長度
print(type(c)) # c的變數型態

[[[7 8]
  [6 6]
  [7 9]]

 [[7 7]
  [0 7]
  [6 4]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[9, 2, 2, 4, 8, 8]
[9, 2, 2, 4, 8, 8]


In [7]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[6, 0, 9, 3], [8, 6, 8, 8], [5, 2, 7, 1]]
[array([6, 0, 9, 3]), array([8, 6, 8, 8]), array([5, 2, 7, 1])]


In [8]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[0, 3], [2, 6], [0, 7]], [[7, 1], [8, 0], [3, 0]]]
[array([[0, 3],
       [2, 6],
       [0, 7]]), array([[7, 1],
       [8, 0],
       [3, 0]])]


In [9]:
def tolist(iterable):
    if(type(iterable) != np.ndarray):
        return iterable
    lst = []
    for element in iterable:
        lst.append(tolist(element))
    return list(lst)
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 2, 2, 4, 8, 8]
[[6, 0, 9, 3], [8, 6, 8, 8], [5, 2, 7, 1]]
[[[0, 3], [2, 6], [0, 7]], [[7, 1], [8, 0], [3, 0]]]


In [10]:
def tolist(iterable):
    if(type(iterable) != np.ndarray):
        return iterable
    return [tolist(element) for element in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 2, 2, 4, 8, 8]
[[6, 0, 9, 3], [8, 6, 8, 8], [5, 2, 7, 1]]
[[[0, 3], [2, 6], [0, 7]], [[7, 1], [8, 0], [3, 0]]]
