# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [4]:
import numpy as np
a = np.arange(5)
print(a.sum()) # 10
print(np.sum(a)) # 10
print(sum(a)) # 10

b = [0, 1, 2, 3, 4]
print(b.sum()) # AttributeError：list無.sum()這個屬性
print(np.sum(b)) # 10
print(sum(b)) # 10

10
10
10


AttributeError: 'list' object has no attribute 'sum'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。
normalization
https://ithelp.ithome.com.tw/articles/10197357
https://blog.csdn.net/kane7csdn/article/details/86475918

In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [5]:
A = np.random.random((5, 5))
print(A)

B = (A - np.min(A)) / (np.max(A) - np.min(A))
print(B)

[[0.65003398 0.61990173 0.31217146 0.87424116 0.31972053]
 [0.6644222  0.33478878 0.77810712 0.83746239 0.87170861]
 [0.23508463 0.47468212 0.47821762 0.63171285 0.04493922]
 [0.69262224 0.34919383 0.38169357 0.83802602 0.48675387]
 [0.9184215  0.22568179 0.62559747 0.86507767 0.89567175]]
[[0.69273845 0.65824175 0.30593893 0.94942045 0.31458144]
 [0.7092107  0.33183222 0.83936208 0.90731453 0.94652108]
 [0.21768663 0.49198812 0.4960357  0.67176364 0.        ]
 [0.74149532 0.34832374 0.38553084 0.9079598  0.50580837]
 [1.         0.20692185 0.66476249 0.93892969 0.9739551 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
a = np.arange(10)
a[a == np.max(a)] = 

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]
